### ISSUE TITLE
Updates README with project purpose

### ISSUE THREAD

**Issue by guiaugusto** [guiaugusto/simple_irc_system#1]
**Description**

It's necessary to create a README that show all that is important about the project, as integrants name, purpose, what is and how to compile it.

**Tasks**

- [ ] Creates topic that explains project context.
- [ ] Creates topic about how to run the project.
- [ ] Creates topic that shows all integrants that made a contribution to the project.
